const data =
  [
    {
      "id": 1,
      "company": "Photosnap",
      "logo": "https://www.bing.com/th?id=OIP.FFg6pWxJoFtzdqeM6MJ6nwAAAA&w=178&h=100&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
      "new": true,
      "featured": true,
      "position": "Senior Frontend Developer",
      "role": "Frontend",
      "level": "Senior",
      "postedAt": "1d ago",
      "contract": "Full Time",
      "location": "USA Only",
      "languages": ["HTML", "CSS", "JavaScript"],
      "tools": []
    },
    {
      "id": 2,
      "company": "Manage",
      "logo": "https://www.bing.com/th?id=OIP.lQFKKgBcti7HzGITpd7ypwHaCe&w=294&h=108&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
      "new": true,
      "featured": true,
      "position": "Fullstack Developer",
      "role": "Fullstack",
      "level": "Midweight",
      "postedAt": "1d ago",
      "contract": "Part Time",
      "location": "Remote",
      "languages": ["Python"],
      "tools": ["React"]
    },
    {
      "id": 3,
      "company": "Account",
      "logo": "https://th.bing.com/th/id/OIP.tSJbzrMMElfojP__jAdOHQHaFo?w=214&h=180&c=7&r=0&o=5&pid=1.7",
      "new": true,
      "featured": false,
      "position": "Junior Frontend Developer",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "2d ago",
      "contract": "Part Time",
      "location": "USA Only",
      "languages": ["JavaScript"],
      "tools": ["React", "Sass"]
    },
    {
      "id": 4,
      "company": "MyHome",
      "logo": "https://th.bing.com/th/id/OIP.6cdk5J-67AwUPBl5GG0_rQHaHa?w=178&h=180&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Junior Frontend Developer",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "5d ago",
      "contract": "Contract",
      "location": "USA Only",
      "languages": ["CSS", "JavaScript"],
      "tools": []
    },
    {
      "id": 5,
      "company": "Loop Studios",
      "logo": "https://th.bing.com/th/id/OIP.ab-9LqOhx4B_5YL1G614JQHaEK?w=307&h=180&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Software Engineer",
      "role": "Fullstack",
      "level": "Midweight",
      "postedAt": "1w ago",
      "contract": "Full Time",
      "location": "Worldwide",
      "languages": ["JavaScript"],
      "tools": ["Ruby", "Sass"]
    },
    {
      "id": 6,
      "company": "FaceIt",
      "logo": "https://th.bing.com/th/id/OIP.t1LGO7s-v0vytNAcojFFvwHaIB?w=173&h=187&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Junior Backend Developer",
      "role": "Backend",
      "level": "Junior",
      "postedAt": "2w ago",
      "contract": "Full Time",
      "location": "UK Only",
      "languages": ["Ruby"],
      "tools": ["RoR"]
    },
    {
      "id": 7,
      "company": "Shortly",
      "logo": "https://th.bing.com/th/id/OIP.SS42Ig6GVs6apGXbBUrb3wHaF7?w=225&h=184&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Junior Developer",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "2w ago",
      "contract": "Full Time",
      "location": "Worldwide",
      "languages": ["HTML", "JavaScript"],
      "tools": ["Sass"]
    },
    {
      "id": 8,
      "company": "Insure",
      "logo": "https://th.bing.com/th/id/OIP.Lfd3Jq3KhMntNCEKUlvXWQHaHa?w=180&h=184&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Junior Frontend Developer",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "2w ago",
      "contract": "Full Time",
      "location": "USA Only",
      "languages": ["JavaScript"],
      "tools": ["Vue", "Sass"]
    },
    {
      "id": 9,
      "company": "Eyecam Co.",
      "logo": "https://th.bing.com/th/id/OIP.ztOQcb4mwNSRw1SS4HPFnwHaFj?w=247&h=185&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Full Stack Engineer",
      "role": "Fullstack",
      "level": "Midweight",
      "postedAt": "3w ago",
      "contract": "Full Time",
      "location": "Worldwide",
      "languages": ["JavaScript", "Python"],
      "tools": ["Django"]
    },
    {
      "id": 10,
      "company": "The Air Filter Company",
      "logo": "https://th.bing.com/th/id/OIP.DSODsWF-drRsPw-CiwZVwwHaEK?w=298&h=180&c=7&r=0&o=5&pid=1.7",
      "new": false,
      "featured": false,
      "position": "Front-end Dev",
      "role": "Frontend",
      "level": "Junior",
      "postedAt": "1mo ago",
      "contract": "Part Time",
      "location": "Worldwide",
      "languages": ["JavaScript"],
      "tools": ["React", "Sass"]
    }
  ]

export default data;